version: "3"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: application_app
    tty: true
    volumes:
      - "./:/usr/app"
      - "/usr/app/node_modules"
    ports:
      - 3000:3000
    command: "yarn nodemon"
    working_dir: "/usr/app"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.2.10-bionic
    restart: always
    container_name: application_mongo
    tty: true
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: development

  mongo-express:
    image: mongo-express
    restart: always
    container_name: application_mongo_express
    tty: true
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: development
      ME_CONFIG_MONGODB_ADMINPASSWORD: development
    depends_on:
      - mongo

  redis:
    image: redis:alpine
    restart: always
    container_name: application_redis
    tty: true
    ports:
      - 6379:6379
