release:
  stage: deploy
  image: dtzar/helm-kubectl
  before_script:
    - sed -i "s~<VERSION>~${CI_COMMIT_TAG}~g" .helm/Chart.yaml
  script:
    - helm upgrade example-com .helm --namespace "${KUBE_NAMESPACE}" --install
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_TAG =~/^\d+\.\d+\.\d+.*?$/
      when: manual
